import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { AppDispatch } from '../store';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ExtractedNutrient {
  name: string;
  value: string;   // e.g. "120 mg", "Low"
  unit?: string;
  flag?: 'normal' | 'high' | 'low';  // NLP-classified status
}

export interface NLPExtractionResult {
  summary: string;           // short narrative generated by NLP
  nutrients: ExtractedNutrient[];
  recommendations: string[];
  risk_flags: string[];      // e.g. ["high cholesterol", "low iron"]
  confidence: number;        // 0 – 1
  raw_text: string;          // original text sent to NLP
}

export interface MedicalReport {
  id: number;
  title: string;
  file: string;              // URL to the uploaded PDF/image
  uploaded_at: string;
  report_type: 'blood_test' | 'urine_test' | 'general' | 'other';
  status: 'pending' | 'processing' | 'done' | 'failed';
  nlp_result: NLPExtractionResult | null;
}

export interface ReportState {
  list: {
    data: MedicalReport[];
    loading: boolean;
    error: string | null;
  };
  upload: {
    loading: boolean;
    error: string | null;
    progress: number;        // 0 – 100
  };
  extraction: {
    loading: boolean;
    error: string | null;
    data: NLPExtractionResult | null;
  };
  selectedReport: MedicalReport | null;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const BASE = 'http://localhost:8000/api';

const loadReportsFromStorage = (): MedicalReport[] => {
  if (typeof window === 'undefined') return [];
  try {
    const stored = localStorage.getItem('medicalReports');
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
};

const saveReportsToStorage = (reports: MedicalReport[]): void => {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem('medicalReports', JSON.stringify(reports));
  } catch {
    // ignore quota errors
  }
};

// ─── Initial State ────────────────────────────────────────────────────────────

const initialState: ReportState = {
  list: {
    data: loadReportsFromStorage(),
    loading: false,
    error: null,
  },
  upload: {
    loading: false,
    error: null,
    progress: 0,
  },
  extraction: {
    loading: false,
    error: null,
    data: null,
  },
  selectedReport: null,
};

// ─── Slice ────────────────────────────────────────────────────────────────────

const reportSlice = createSlice({
  name: 'report',
  initialState,
  reducers: {
    // List
    setReportsLoading: (state, action: PayloadAction<boolean>) => {
      state.list.loading = action.payload;
    },
    setReportsError: (state, action: PayloadAction<string | null>) => {
      state.list.error = action.payload;
    },
    setReportsData: (state, action: PayloadAction<MedicalReport[]>) => {
      state.list.data = action.payload;
      state.list.loading = false;
      state.list.error = null;
      saveReportsToStorage(action.payload);
    },
    addReport: (state, action: PayloadAction<MedicalReport>) => {
      state.list.data.unshift(action.payload);
      saveReportsToStorage(state.list.data);
    },
    updateReport: (state, action: PayloadAction<MedicalReport>) => {
      const idx = state.list.data.findIndex((r) => r.id === action.payload.id);
      if (idx !== -1) {
        state.list.data[idx] = action.payload;
        saveReportsToStorage(state.list.data);
      }
    },
    removeReport: (state, action: PayloadAction<number>) => {
      state.list.data = state.list.data.filter((r) => r.id !== action.payload);
      saveReportsToStorage(state.list.data);
    },
    clearReports: (state) => {
      state.list = { data: [], loading: false, error: null };
      saveReportsToStorage([]);
    },

    // Upload
    setUploadLoading: (state, action: PayloadAction<boolean>) => {
      state.upload.loading = action.payload;
    },
    setUploadError: (state, action: PayloadAction<string | null>) => {
      state.upload.error = action.payload;
    },
    setUploadProgress: (state, action: PayloadAction<number>) => {
      state.upload.progress = action.payload;
    },
    resetUpload: (state) => {
      state.upload = { loading: false, error: null, progress: 0 };
    },

    // NLP Extraction
    setExtractionLoading: (state, action: PayloadAction<boolean>) => {
      state.extraction.loading = action.payload;
    },
    setExtractionError: (state, action: PayloadAction<string | null>) => {
      state.extraction.error = action.payload;
    },
    setExtractionData: (state, action: PayloadAction<NLPExtractionResult | null>) => {
      state.extraction.data = action.payload;
      state.extraction.loading = false;
      state.extraction.error = null;
    },
    clearExtraction: (state) => {
      state.extraction = { loading: false, error: null, data: null };
    },

    // Selected report
    setSelectedReport: (state, action: PayloadAction<MedicalReport | null>) => {
      state.selectedReport = action.payload;
    },

    clearAllReportErrors: (state) => {
      state.list.error = null;
      state.upload.error = null;
      state.extraction.error = null;
    },
  },
});

export const {
  setReportsLoading,
  setReportsError,
  setReportsData,
  addReport,
  updateReport,
  removeReport,
  clearReports,
  setUploadLoading,
  setUploadError,
  setUploadProgress,
  resetUpload,
  setExtractionLoading,
  setExtractionError,
  setExtractionData,
  clearExtraction,
  setSelectedReport,
  clearAllReportErrors,
} = reportSlice.actions;

// ─── Thunks ───────────────────────────────────────────────────────────────────

/**
 * Fetch all medical reports for the current user.
 */
export const fetchReports =
  () => async (dispatch: AppDispatch) => {
    try {
      dispatch(setReportsLoading(true));
      dispatch(setReportsError(null));

      const res = await fetch(`${BASE}/reports/`, {
        method: 'GET',
        credentials: 'include',
      });

      if (!res.ok) throw new Error(`${res.status}: ${res.statusText}`);

      const data: MedicalReport[] = await res.json();
      dispatch(setReportsData(data));
      return data;
    } catch {
      dispatch(setReportsLoading(false));
      dispatch(setReportsError('Using saved data'));
      return [];
    }
  };

/**
 * Upload a new medical report file (PDF or image).
 * Dispatches upload progress and adds the created report to the list.
 */
export const uploadReport =
  (file: File, title: string, reportType: MedicalReport['report_type'] = 'general') =>
  async (dispatch: AppDispatch) => {
    try {
      dispatch(setUploadLoading(true));
      dispatch(setUploadError(null));
      dispatch(setUploadProgress(0));

      const formData = new FormData();
      formData.append('file', file);
      formData.append('title', title);
      formData.append('report_type', reportType);

      // Use XMLHttpRequest so we can track upload progress
      const report = await new Promise<MedicalReport>((resolve, reject) => {
        const xhr = new XMLHttpRequest();

        xhr.upload.addEventListener('progress', (e) => {
          if (e.lengthComputable) {
            dispatch(setUploadProgress(Math.round((e.loaded / e.total) * 100)));
          }
        });

        xhr.addEventListener('load', () => {
          if (xhr.status >= 200 && xhr.status < 300) {
            resolve(JSON.parse(xhr.responseText) as MedicalReport);
          } else {
            reject(new Error(`${xhr.status}: ${xhr.statusText}`));
          }
        });

        xhr.addEventListener('error', () => reject(new Error('Network error')));

        xhr.open('POST', `${BASE}/reports/upload/`);
        xhr.withCredentials = true;
        xhr.send(formData);
      });

      dispatch(addReport(report));
      dispatch(setUploadProgress(100));
      dispatch(setUploadLoading(false));
      return report;
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Upload failed';
      dispatch(setUploadError(msg));
      dispatch(setUploadLoading(false));
      throw error;
    }
  };

/**
 * Delete a report by ID.
 */
export const deleteReport =
  (reportId: number) => async (dispatch: AppDispatch) => {
    try {
      const res = await fetch(`${BASE}/reports/${reportId}/`, {
        method: 'DELETE',
        credentials: 'include',
      });
      if (!res.ok) throw new Error(`${res.status}: ${res.statusText}`);
      dispatch(removeReport(reportId));
      return { success: true };
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Delete failed';
      throw new Error(msg);
    }
  };

/**
 * Extract nutritional data from a report using the backend NLP pipeline.
 * The backend reads the PDF/image, runs NLP, and returns structured data.
 *
 * @param reportId  ID of an already-uploaded report
 * @param rawText   Optional plain text override (if caller already has OCR output)
 */
export const extractReportWithNLP =
  (reportId: number, rawText?: string) => async (dispatch: AppDispatch) => {
    try {
      dispatch(setExtractionLoading(true));
      dispatch(setExtractionError(null));

      const body: Record<string, unknown> = { report_id: reportId };
      if (rawText) body.raw_text = rawText;

      const res = await fetch(`${BASE}/reports/extract/`, {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });

      if (!res.ok) throw new Error(`${res.status}: ${res.statusText}`);

      const nlpResult: NLPExtractionResult = await res.json();

      dispatch(setExtractionData(nlpResult));

      // Patch the report in the list so its nlp_result is up-to-date
      dispatch(
        updateReport({
          id: reportId,
          nlp_result: nlpResult,
          status: 'done',
        } as MedicalReport)
      );

      return nlpResult;
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'NLP extraction failed';
      dispatch(setExtractionError(msg));
      throw error;
    }
  };

// ─── Selectors ────────────────────────────────────────────────────────────────

export const selectReportList       = (state: { report: ReportState }) => state.report.list;
export const selectUpload           = (state: { report: ReportState }) => state.report.upload;
export const selectExtraction       = (state: { report: ReportState }) => state.report.extraction;
export const selectSelectedReport   = (state: { report: ReportState }) => state.report.selectedReport;

// ─── Reducer export ───────────────────────────────────────────────────────────

export default reportSlice.reducer;
